import type { SafetyReport } from '../types/reports';
import type { PrecursorPattern } from '../types/patterns';
import type { HSEIntervention } from '../types/interventions';
import type { AuditLogEntry } from '../types/audit';
import type { DashboardOverviewResponse } from '../types/dashboard';

/**
 * ============================================================================
 * SYNTHETIC / DEMO DATASET FOR OIL INDIA LIMITED (SIH26165)
 * NOTE: This data is realistic synthetic data generated solely for system
 * testing, demonstration, and frontend standalone operation.
 * ============================================================================
 */

export const MOCK_REPORTS: SafetyReport[] = [
  {
    id: 'OIL-2026-R001',
    title: 'Pump motor maintenance initiated prior to circuit breaker lock-out',
    type: 'Unsafe Act',
    date: '2026-02-28T09:30:00Z',
    site: 'Duliajan Central Complex',
    department: 'Electrical Maintenance',
    location_detail: 'Crude Desalting Unit (CDU-2) Pump House',
    activity: 'Maintenance',
    reporter_name: 'Debojit Phukan',
    reporter_role: 'Electrical Supervisor',
    description: 'During scheduled maintenance of crude transfer pump P-204B, technicians commenced coupling removal and terminal box opening while the 415V feeder breaker in MCC-3 was tagged but lacked a physical padlock lockout and had not undergone zero-voltage verification at the motor terminals.',
    immediate_actions_taken: 'Work stopped immediately. Padlock applied at MCC feeder and zero-energy test verified by HSE supervisor before permitting work resumption.',
    sif_status: 'SIF_POTENTIAL',
    sif_score: 0.94,
    life_saving_rule: 'Energy Isolation',
    priority: 'CRITICAL',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-28T10:00:00Z',
    updated_at: '2026-02-28T10:05:00Z',
    investigation_status: 'Intervention Scheduled',
    ai_result: {
      report_id: 'OIL-2026-R001',
      sif: { label: 'SIF_POTENTIAL', score: 0.94 },
      life_saving_rules: [
        { name: 'Energy Isolation', score: 0.96 },
        { name: 'Work Authorization', score: 0.72 },
      ],
      precursors: {
        activity: 'Maintenance',
        hazard: '415V Hazardous Electrical Energy',
        barrier_failure: 'Incomplete Energy Isolation & Zero-Voltage Verification',
        potential_consequence: 'Electrocution & Arc-Flash Fatality',
      },
      explanation: 'The report describes mechanical and electrical maintenance work commencing on a high-voltage industrial pump prior to full physical lockout and zero-voltage verification. This represents an acute Energy Isolation barrier failure with high SIF potential for fatal electrocution.',
      patterns: ['PAT-001: Energy Isolation & LOTO Non-Compliance'],
      priority: 'CRITICAL',
      analyzed_at: '2026-02-28T10:05:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R002',
    title: 'Gas cutting sparks directed toward unblanked hydrocarbon manifold',
    type: 'Unsafe Condition',
    date: '2026-02-27T14:15:00Z',
    site: 'Moran Oil & Gas Field',
    department: 'Mechanical Operations',
    location_detail: 'Gas Compressor Station 4',
    activity: 'Hot Work',
    reporter_name: 'Bhaben Gogoi',
    reporter_role: 'Safety Officer',
    description: 'Contractor welding team commenced oxy-acetylene torch cutting of structural brackets within 4.5 meters of a condensate drain line. While a hot work permit was issued, flame-retardant fire blankets were not deployed and continuous combustible gas detector was powered off.',
    immediate_actions_taken: 'Hot work permit revoked immediately. Area isolated, gas testing conducted (LEL 0%), and habitat spark enclosure erected before re-authorizing work.',
    sif_status: 'SIF_POTENTIAL',
    sif_score: 0.89,
    life_saving_rule: 'Hot Work',
    priority: 'CRITICAL',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-27T14:30:00Z',
    updated_at: '2026-02-27T14:35:00Z',
    investigation_status: 'Under Review',
    ai_result: {
      report_id: 'OIL-2026-R002',
      sif: { label: 'SIF_POTENTIAL', score: 0.89 },
      life_saving_rules: [
        { name: 'Hot Work', score: 0.94 },
        { name: 'Work Authorization', score: 0.68 },
      ],
      precursors: {
        activity: 'Hot Work / Oxy-Acetylene Cutting',
        hazard: 'Flammable Hydrocarbon Gas & Condensate',
        barrier_failure: 'Absence of Spark Containment & Powered-off Gas Monitor',
        potential_consequence: 'Hydrocarbon Vapor Cloud Explosion & Fire',
      },
      explanation: 'Open flame cutting conducted adjacent to live condensate drain lines without spark barriers and without active gas monitoring represents a severe failure of ignition control barriers with catastrophic explosion potential.',
      patterns: ['PAT-002: Hot Work Spark Containment Breakdown'],
      priority: 'CRITICAL',
      analyzed_at: '2026-02-27T14:35:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R003',
    title: 'Drill collar sling slippage during monkey board transfer',
    type: 'Near-Miss',
    date: '2026-02-26T11:00:00Z',
    site: 'Naharkatiya Production Station',
    department: 'Drilling & Well Services',
    location_detail: 'Drilling Rig OIL-DR-07 Rig Floor',
    activity: 'Rig Floor Operations',
    reporter_name: 'Anup Kumar Barua',
    reporter_role: 'Rig Toolpusher',
    description: 'While lifting an 8-inch drill collar (approx 2.4 tons) from the pipe rack to the rig floor, single nylon sling slipped due to grease contamination and lack of a dual-tagline control. The load swung violently into the rotary table area where two floormen were standing 1.5m away.',
    immediate_actions_taken: 'Rig floor cleared. Uncertified nylon sling condemned. Mandatory certified wire-rope slings with choke-hitch shackles implemented for all drill tubular lifts.',
    sif_status: 'SIF_POTENTIAL',
    sif_score: 0.92,
    life_saving_rule: 'Safe Mechanical Lifting',
    priority: 'CRITICAL',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-26T11:30:00Z',
    updated_at: '2026-02-26T11:35:00Z',
    investigation_status: 'Intervention Scheduled',
    ai_result: {
      report_id: 'OIL-2026-R003',
      sif: { label: 'SIF_POTENTIAL', score: 0.92 },
      life_saving_rules: [
        { name: 'Safe Mechanical Lifting', score: 0.95 },
        { name: 'Line of Fire', score: 0.88 },
      ],
      precursors: {
        activity: 'Rig Floor Operations / Tubular Hoisting',
        hazard: 'Suspended 2.4-ton Drill Collar / Stored Gravitational Energy',
        barrier_failure: 'Improper Rigging Hitch & Personnel within Exclusion Radius',
        potential_consequence: 'Crush Impact / Struck-by Fatality',
      },
      explanation: 'Slippage of heavy tubular load suspended above floor crew with failed exclusion zone discipline. High probability of fatal crush injury in line-of-fire event.',
      patterns: ['PAT-003: Rig Floor Tubular Lifting & Line-of-Fire Risks'],
      priority: 'CRITICAL',
      analyzed_at: '2026-02-26T11:35:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R004',
    title: 'Crude storage tank entry conducted with single-point gas test',
    type: 'Unsafe Condition',
    date: '2026-02-25T16:20:00Z',
    site: 'Digboi Refinery Asset',
    department: 'Tank Farm Operations',
    location_detail: 'Tank TK-104 (Fixed Roof Crude Storage)',
    activity: 'Confined Space Tank Cleaning',
    reporter_name: 'Priyanka Saikia',
    reporter_role: 'HSE Analyst',
    description: 'Sludge cleaning squad entered 50,000 bbl crude tank TK-104 based on an atmospheric test performed solely at the bottom manway. Multi-level stratified testing for H2S and oxygen deficiency was omitted, and forced mechanical ventilation duct had become disconnected.',
    immediate_actions_taken: 'Squad evacuated from tank immediately. Ventilation reinstated. 3-level atmospheric testing instituted with continuous multi-gas monitor wearable by entrants.',
    sif_status: 'SIF_POTENTIAL',
    sif_score: 0.95,
    life_saving_rule: 'Confined Space',
    priority: 'CRITICAL',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-25T16:45:00Z',
    updated_at: '2026-02-25T16:50:00Z',
    investigation_status: 'Open',
    ai_result: {
      report_id: 'OIL-2026-R004',
      sif: { label: 'SIF_POTENTIAL', score: 0.95 },
      life_saving_rules: [
        { name: 'Confined Space', score: 0.98 },
        { name: 'Toxic Gas / Work Authorization', score: 0.84 },
      ],
      precursors: {
        activity: 'Confined Space Tank Cleaning',
        hazard: 'Stratified H2S & Oxygen Depleted Atmosphere',
        barrier_failure: 'Inadequate Multi-Level Gas Testing & Failed Ventilation',
        potential_consequence: 'Toxic Asphyxiation / Multiple Fatalities',
      },
      explanation: 'Entry into hydrocarbon tank without stratified atmosphere verification and with degraded ventilation duct. Severe precursor for catastrophic toxic asphyxiation.',
      patterns: ['PAT-004: Confined Space Atmospheric Verification Lapses'],
      priority: 'CRITICAL',
      analyzed_at: '2026-02-25T16:50:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R005',
    title: 'Derrickman working unhooked on monkey board during tubing pull',
    type: 'Unsafe Act',
    date: '2026-02-24T08:45:00Z',
    site: 'Jorhat Drilling Block',
    department: 'Well Servicing',
    location_detail: 'Workover Rig WOR-03 Mast at 22 meters',
    activity: 'Working at Height',
    reporter_name: 'Manas Jyoti Dutta',
    reporter_role: 'HSE Inspector',
    description: 'During tubing pulling operations at 22 meters elevation, the derrickman unclipped the dual lanyard from the inertia reel anchor while stepping across the monkey board finger to free a stuck latch.',
    immediate_actions_taken: 'Operation halted. Derrickman instructed to secure 100% tie-off. Stand-down briefing conducted with crew on fall arrest protocol.',
    sif_status: 'SIF_POTENTIAL',
    sif_score: 0.88,
    life_saving_rule: 'Working at Height',
    priority: 'HIGH',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-24T09:10:00Z',
    updated_at: '2026-02-24T09:15:00Z',
    investigation_status: 'Closed',
    ai_result: {
      report_id: 'OIL-2026-R005',
      sif: { label: 'SIF_POTENTIAL', score: 0.88 },
      life_saving_rules: [
        { name: 'Working at Height', score: 0.97 },
      ],
      precursors: {
        activity: 'Working at Height / Derrick Operations',
        hazard: 'Elevated Fall Risk (22 meters height)',
        barrier_failure: 'Breach of 100% Tie-Off Rule & Inertia Reel Disconnect',
        potential_consequence: 'Fatal Fall from Height',
      },
      explanation: 'Operating at 22m elevation without continuous fall arrest tie-off. Direct high-energy precursor for fatal fall.',
      patterns: ['PAT-005: Working at Height Tie-off Disconnects'],
      priority: 'HIGH',
      analyzed_at: '2026-02-24T09:15:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R006',
    title: 'High-pressure gas manifold bypass valve locked in open position',
    type: 'Unsafe Condition',
    date: '2026-02-23T13:10:00Z',
    site: 'Duliajan Central Complex',
    department: 'Process Operations',
    location_detail: 'Gas Separation Unit 2, High Pressure Header',
    activity: 'Process Plant Operations',
    reporter_name: 'Sanjoy Bora',
    reporter_role: 'Control Room Operator',
    description: 'During field routine round, manual bypass valve across Emergency Shutdown Valve (ESDV-102) was found unlocked and in 30% open position, bypassing automated pressure trip protection.',
    immediate_actions_taken: 'Bypass valve fully closed and car-sealed closed. Management of Change (MOC) register inspected and ESD logic retested.',
    sif_status: 'SIF_POTENTIAL',
    sif_score: 0.87,
    life_saving_rule: 'Bypassing Safety Controls',
    priority: 'HIGH',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-23T13:30:00Z',
    updated_at: '2026-02-23T13:35:00Z',
    investigation_status: 'Intervention Scheduled',
    ai_result: {
      report_id: 'OIL-2026-R006',
      sif: { label: 'SIF_POTENTIAL', score: 0.87 },
      life_saving_rules: [
        { name: 'Bypassing Safety Controls', score: 0.94 },
      ],
      precursors: {
        activity: 'Process Plant Operations',
        hazard: 'Overpressure of 90 bar Gas Header',
        barrier_failure: 'Unauthorized Mechanical Override of Safety Shutdown Barrier',
        potential_consequence: 'Piping Rupture & Catastrophic Gas Release',
      },
      explanation: 'Compromise of primary automated overpressure protection via unauthorized bypass valve position.',
      patterns: ['PAT-006: Safety Critical Equipment Bypass'],
      priority: 'HIGH',
      analyzed_at: '2026-02-23T13:35:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R007',
    title: 'Heavy transport trailer operating without journey management approval',
    type: 'Unsafe Act',
    date: '2026-02-22T18:00:00Z',
    site: 'Numaligarh Pipeline Corridor',
    department: 'Logistics & Transport',
    location_detail: 'Section 3 River Crossing Road Access',
    activity: 'Driving & Transport',
    reporter_name: 'Hitesh Das',
    reporter_role: 'Transport Officer',
    description: 'Articulated heavy truck transporting 40-foot coated pipe sections operated after dusk along restricted narrow single-lane embankment road without pilot vehicle and with defective right-side brake lights.',
    immediate_actions_taken: 'Vehicle halted at checkpoint. Night transit prohibited. Defective lighting repaired before next morning transit under escort.',
    sif_status: 'SIF_POTENTIAL',
    sif_score: 0.76,
    life_saving_rule: 'Driving',
    priority: 'MEDIUM',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-22T18:30:00Z',
    updated_at: '2026-02-22T18:35:00Z',
    investigation_status: 'Closed',
    ai_result: {
      report_id: 'OIL-2026-R007',
      sif: { label: 'SIF_POTENTIAL', score: 0.76 },
      life_saving_rules: [
        { name: 'Driving', score: 0.91 },
      ],
      precursors: {
        activity: 'Heavy Equipment Transport',
        hazard: 'Vehicle Rollover / Road Traffic Collision',
        barrier_failure: 'Journey Management Non-Compliance & Lighting Defect',
        potential_consequence: 'Rollover Collision & Major Injury',
      },
      explanation: 'Violation of night-driving restrictions for oversized tubular loads on unlit embankment road.',
      patterns: ['PAT-007: Logistics & Journey Management Breaches'],
      priority: 'MEDIUM',
      analyzed_at: '2026-02-22T18:35:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R008',
    title: 'Damaged insulation tape on 24V inspection handheld lamp',
    type: 'Unsafe Condition',
    date: '2026-02-21T10:15:00Z',
    site: 'Kumchai Exploration Field',
    department: 'Electrical Maintenance',
    location_detail: 'Workshop Bay 2',
    activity: 'Workshop Maintenance',
    reporter_name: 'Tarun Sarma',
    reporter_role: 'Electrician',
    description: 'Minor frayed insulation observed on the extra-low-voltage (24V SELV) portable inspection lamp cable. Transformer unit was properly grounded and tested.',
    immediate_actions_taken: 'Lamp taken out of service and cable replaced with new industrial grade flexible lead.',
    sif_status: 'NON_SIF',
    sif_score: 0.12,
    life_saving_rule: 'Energy Isolation',
    priority: 'LOW',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-21T10:30:00Z',
    updated_at: '2026-02-21T10:35:00Z',
    investigation_status: 'Closed',
    ai_result: {
      report_id: 'OIL-2026-R008',
      sif: { label: 'NON_SIF', score: 0.12 },
      life_saving_rules: [
        { name: 'Energy Isolation', score: 0.25 },
      ],
      precursors: {
        activity: 'Workshop Maintenance',
        hazard: 'Low-Voltage (24V) Electrical Current',
        barrier_failure: 'Minor Cable Sheath Wear',
        potential_consequence: 'Minor shock / Non-injurious fault',
      },
      explanation: 'Operating on safety extra-low voltage (24V SELV). Hazard energy insufficient to cause serious injury or fatality.',
      patterns: [],
      priority: 'LOW',
      analyzed_at: '2026-02-21T10:35:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R009',
    title: 'Minor paint overspray near chemical storage shed walkway',
    type: 'Unsafe Condition',
    date: '2026-02-20T15:00:00Z',
    site: 'Digboi Refinery Asset',
    department: 'Civil Maintenance',
    location_detail: 'Warehouse Perimeter',
    activity: 'Civil Works',
    reporter_name: 'Ratul Borah',
    reporter_role: 'Civil Inspector',
    description: 'Overspray from boundary wall repainting made walking surface slightly slippery when wet. Anti-slip grip tape was partially worn on the 2-step entrance ramp.',
    immediate_actions_taken: 'Surface cleaned and anti-slip stair nosing installed.',
    sif_status: 'NON_SIF',
    sif_score: 0.18,
    life_saving_rule: 'Work Authorization',
    priority: 'LOW',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-20T15:15:00Z',
    updated_at: '2026-02-20T15:20:00Z',
    investigation_status: 'Closed',
    ai_result: {
      report_id: 'OIL-2026-R009',
      sif: { label: 'NON_SIF', score: 0.18 },
      life_saving_rules: [
        { name: 'Work Authorization', score: 0.15 },
      ],
      precursors: {
        activity: 'Civil Works / Housekeeping',
        hazard: 'Low-level Slip/Trip Hazard at Ground Level',
        barrier_failure: 'Worn Stair Traction Strip',
        potential_consequence: 'Minor Slip / Sprain',
      },
      explanation: 'Ground-level slip hazard without high energy or severe drop height. No SIF precursor identified.',
      patterns: [],
      priority: 'LOW',
      analyzed_at: '2026-02-20T15:20:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R010',
    title: 'High-pressure water jetting hose connection found with missing whip-check',
    type: 'Unsafe Condition',
    date: '2026-02-19T11:40:00Z',
    site: 'Moran Oil & Gas Field',
    department: 'Pipeline Integrity',
    location_detail: 'Manifold Hydrotesting Bay',
    activity: 'Pipeline Pressure Testing',
    reporter_name: 'Dipen Hazarika',
    reporter_role: 'Hydrotest Lead',
    description: '10,000 PSI hydro-jetting hose coupling connected to diesel pump unit without safety whip-check cable or locking pin attached. Pressure gauge read 6,800 PSI during line de-scaling.',
    immediate_actions_taken: 'Pressure bled down immediately. Whip-check safety cables installed across all high-pressure flexible joints before restarting pump.',
    sif_status: 'SIF_POTENTIAL',
    sif_score: 0.91,
    life_saving_rule: 'Line of Fire',
    priority: 'CRITICAL',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-19T12:00:00Z',
    updated_at: '2026-02-19T12:05:00Z',
    investigation_status: 'Under Review',
    ai_result: {
      report_id: 'OIL-2026-R010',
      sif: { label: 'SIF_POTENTIAL', score: 0.91 },
      life_saving_rules: [
        { name: 'Line of Fire', score: 0.96 },
        { name: 'Energy Isolation', score: 0.74 },
      ],
      precursors: {
        activity: 'Pipeline Pressure Testing / Hydro-Jetting',
        hazard: 'Ultra-High Hydraulic Pressure (6,800 PSI)',
        barrier_failure: 'Missing Whip-Check Restraint on Pressurized Coupling',
        potential_consequence: 'Hose Whiplash / High-Pressure Fluid Injection Fatality',
      },
      explanation: 'Pressurized hydraulic line operated without mechanical whipping restraint. Hose parting at 6,800 PSI represents extreme risk of lethal kinetic impact or fluid skin-penetration.',
      patterns: ['PAT-008: High Pressure Testing & Whip-Check Omission'],
      priority: 'CRITICAL',
      analyzed_at: '2026-02-19T12:05:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R011',
    title: 'Temporary scaffold erected without diagonal bracing over trench',
    type: 'Unsafe Condition',
    date: '2026-02-18T14:00:00Z',
    site: 'Duliajan Central Complex',
    department: 'Civil Maintenance',
    location_detail: 'Gas Pipeline Trenching Area West',
    activity: 'Working at Height',
    reporter_name: 'Bikash Sonowal',
    reporter_role: 'Civil Supervisor',
    description: 'Scaffold structure of 4.2m height erected over 2m deep open excavation lacked longitudinal sway bracing and base plates on soft backfilled soil, showing visible 5-degree deflection under load.',
    immediate_actions_taken: 'Red "DO NOT USE" scaffold tag affixed. Scaffold dismantled and re-erected with certified sole boards and cross braces under competent supervisor.',
    sif_status: 'SIF_POTENTIAL',
    sif_score: 0.85,
    life_saving_rule: 'Working at Height',
    priority: 'HIGH',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-18T14:30:00Z',
    updated_at: '2026-02-18T14:35:00Z',
    investigation_status: 'Closed',
    ai_result: {
      report_id: 'OIL-2026-R011',
      sif: { label: 'SIF_POTENTIAL', score: 0.85 },
      life_saving_rules: [
        { name: 'Working at Height', score: 0.93 },
      ],
      precursors: {
        activity: 'Working at Height / Scaffolding',
        hazard: 'Combined Height + Trench Depth (6.2m effective fall)',
        barrier_failure: 'Structural Scaffold Instability & Missing Bracing',
        potential_consequence: 'Scaffold Collapse / Severe Trauma / Fatality',
      },
      explanation: 'Compromised scaffold integrity over deep trench presents cumulative 6m+ fall height and structural collapse hazard.',
      patterns: ['PAT-005: Working at Height & Temporary Works Weaknesses'],
      priority: 'HIGH',
      analyzed_at: '2026-02-18T14:35:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
  {
    id: 'OIL-2026-R012',
    title: 'Contractor welding team entered flare header zone without toxic gas briefing',
    type: 'Near-Miss',
    date: '2026-02-17T09:10:00Z',
    site: 'Naharkatiya Production Station',
    department: 'Plant Operations',
    location_detail: 'Flare Knockout Drum Knockout Area',
    activity: 'Hot Work',
    reporter_name: 'Mukesh Kalita',
    reporter_role: 'Operations Engineer',
    description: 'Contractor crew engaged in pipe support painting entered within 15 meters of the active flare knockout drum while high-H2S associated gas flaring was active, without personal H2S detectors or wind-sock orientation check.',
    immediate_actions_taken: 'Crew ordered to upwind assembly point. Personal 4-gas detectors issued and H2S emergency breathing apparatus drill completed before job re-start.',
    sif_status: 'SIF_POTENTIAL',
    sif_score: 0.93,
    life_saving_rule: 'Work Authorization',
    priority: 'CRITICAL',
    analysis_status: 'COMPLETED',
    created_at: '2026-02-17T09:30:00Z',
    updated_at: '2026-02-17T09:35:00Z',
    investigation_status: 'Intervention Scheduled',
    ai_result: {
      report_id: 'OIL-2026-R012',
      sif: { label: 'SIF_POTENTIAL', score: 0.93 },
      life_saving_rules: [
        { name: 'Work Authorization', score: 0.94 },
        { name: 'Confined Space', score: 0.70 },
      ],
      precursors: {
        activity: 'Plant Operations / Maintenance near Flare Header',
        hazard: 'Hydrogen Sulfide (H2S) Toxic Gas Release',
        barrier_failure: 'Absence of Personal H2S Detection & Upwind Position Awareness',
        potential_consequence: 'Instant Toxic H2S Inhalation Knockdown / Fatality',
      },
      explanation: 'Personnel working in designated H2S release hazard boundary without personal gas monitors or escape hoods.',
      patterns: ['PAT-004: Toxic Gas Awareness & Detection Deficits'],
      priority: 'CRITICAL',
      analyzed_at: '2026-02-17T09:35:00Z',
      model_version: 'SIF-NLP-v2.4',
    },
  },
];

export const MOCK_PATTERNS: PrecursorPattern[] = [
  {
    id: 'PAT-001',
    name: 'Energy Isolation Failure during Turnaround & Maintenance',
    description: 'Recurring breakdown in Lockout/Tagout (LOTO) physical padlock application and zero-voltage verification prior to motor or valve maintenance.',
    reportCount: 247,
    mainActivity: 'Maintenance & Overhaul',
    mostAffectedSite: 'Duliajan Central Complex',
    sifPotentialRate: 0.81,
    priority: 'CRITICAL',
    primaryLifeSavingRule: 'Energy Isolation',
    keyHazards: ['415V/3.3kV Electrical Energy', 'Stored Pressurized Hydraulic Energy', 'Thermal Steam'],
    commonBarrierFailures: ['Tag placed without physical padlock', 'Missing multi-point zero-voltage test', 'Incomplete LOTO register sign-off'],
    firstDetected: '2025-08-14',
    lastOccurrence: '2026-02-28',
    trendStatus: 'SURGING',
    recommendedIntervention: 'Institute mandatory double-signature Zero Energy Verification checklists and universal LOTO lockbox stations at all electrical distribution substations.',
    matchedReportIds: ['OIL-2026-R001', 'OIL-2026-R006', 'OIL-2026-R008'],
  },
  {
    id: 'PAT-002',
    name: 'Hot Work Spark Containment & Gas Testing Deficits',
    description: 'Welding, torch cutting, and grinding activities conducted with missing flame retardant barriers or deactivated continuous gas detection near hydrocarbon headers.',
    reportCount: 184,
    mainActivity: 'Hot Work & Pipe Welding',
    mostAffectedSite: 'Moran Oil & Gas Field',
    sifPotentialRate: 0.78,
    priority: 'CRITICAL',
    primaryLifeSavingRule: 'Hot Work',
    keyHazards: ['Condensate Vapors', 'Natural Gas Flammables', 'Oxy-Acetylene Cylinders'],
    commonBarrierFailures: ['Non-certified fire blankets', 'Intermittent instead of continuous gas monitoring', 'Inadequate distance to drain sumps'],
    firstDetected: '2025-09-02',
    lastOccurrence: '2026-02-27',
    trendStatus: 'RECURRING',
    recommendedIntervention: 'Deploy calibrated automatic continuous area gas monitors with audible sirens for all Class-1 Division-1 hot work permits.',
    matchedReportIds: ['OIL-2026-R002', 'OIL-2026-R012'],
  },
  {
    id: 'PAT-003',
    name: 'Drilling Rig Tubular Hoisting & Line-of-Fire Breaches',
    description: 'Personnel standing within the swing radius of suspended drill collars, casing joints, and heavy equipment during rig floor transfers.',
    reportCount: 142,
    mainActivity: 'Rig Floor Operations',
    mostAffectedSite: 'Naharkatiya Production Station',
    sifPotentialRate: 0.74,
    priority: 'CRITICAL',
    primaryLifeSavingRule: 'Safe Mechanical Lifting',
    keyHazards: ['Heavy Tubulars (2-10 Tons)', 'Winch Wire Rope Tension', 'Rotary Table Pinch Points'],
    commonBarrierFailures: ['Single-sling rigging instead of certified double-choke', 'Missing exclusion zone barriers on drill floor', 'No hands-free push poles used'],
    firstDetected: '2025-10-18',
    lastOccurrence: '2026-02-26',
    trendStatus: 'RECURRING',
    recommendedIntervention: 'Implement painted red exclusion zone flooring and enforce hands-free lifting tools (magnetic guiding poles) across all active drilling rigs.',
    matchedReportIds: ['OIL-2026-R003'],
  },
  {
    id: 'PAT-004',
    name: 'Confined Space Stratified Atmospheric Testing Lapses',
    description: 'Entry into storage tanks, separator vessels, and sumps with single-elevation gas testing instead of stratified top/middle/bottom testing.',
    reportCount: 96,
    mainActivity: 'Confined Space Tank Cleaning',
    mostAffectedSite: 'Digboi Refinery Asset',
    sifPotentialRate: 0.86,
    priority: 'CRITICAL',
    primaryLifeSavingRule: 'Confined Space',
    keyHazards: ['H2S Toxic Gas', 'Oxygen Depletion (<19.5%)', 'Hydrocarbon Vapors (>10% LEL)'],
    commonBarrierFailures: ['Single bottom manway probe only', 'Ventilation blower duct disconnect', 'Standby attendant absent during shift change'],
    firstDetected: '2025-11-05',
    lastOccurrence: '2026-02-25',
    trendStatus: 'STABLE',
    recommendedIntervention: 'Mandate digital 3-point automated datalogging gas tests and wireless synchronized entrant badges before opening entry permits.',
    matchedReportIds: ['OIL-2026-R004', 'OIL-2026-R012'],
  },
  {
    id: 'PAT-005',
    name: 'Working at Height 100% Tie-Off Lapses on Derricks & Masts',
    description: 'Workers unhooking dual lanyards when transitioning between scaffold levels, monkey boards, and mast work platforms.',
    reportCount: 118,
    mainActivity: 'Working at Height',
    mostAffectedSite: 'Jorhat Drilling Block',
    sifPotentialRate: 0.69,
    priority: 'HIGH',
    primaryLifeSavingRule: 'Working at Height',
    keyHazards: ['Fall Distance > 6 meters', 'Dropped Hand Tools', 'Unguarded Floor Openings'],
    commonBarrierFailures: ['Single lanyard unclipping during transition', 'Inadequately rated scaffolding baseplates', 'Missing tool tether lanyards'],
    firstDetected: '2025-07-20',
    lastOccurrence: '2026-02-24',
    trendStatus: 'DECLINING',
    recommendedIntervention: 'Upgrade all monkey boards with continuous overhead horizontal lifeline cable systems allowing continuous glide without unhooking.',
    matchedReportIds: ['OIL-2026-R005', 'OIL-2026-R011'],
  },
];

export const MOCK_INTERVENTIONS: HSEIntervention[] = [
  {
    id: 'INT-2026-001',
    title: 'Universal LOTO Lockbox & Multi-Point Zero-Energy Verification Protocol',
    category: 'Process Safety Barrier',
    description: 'Rollout of heavy-duty group lockboxes, color-coded padlocks, and mandatory secondary supervisor sign-off on 415V/3.3kV MCC isolation breakers.',
    triggerSource: 'Pattern Detection',
    targetSite: 'Duliajan Central Complex',
    targetActivity: 'Maintenance & Overhaul',
    associatedRule: 'Energy Isolation',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    assignedOfficer: 'Debojit Phukan',
    assignedOfficerRole: 'Lead HSE Electrical Engineer',
    dueDate: '2026-03-25',
    createdDate: '2026-02-15',
    relatedReportIds: ['OIL-2026-R001', 'OIL-2026-R006'],
    patternId: 'PAT-001',
    actionsTaken: [
      'Procured 120 explosion-proof LOTO stations',
      'Completed practical refresher training for 85 electrical technicians',
      'Drafted revised SOP for zero-energy voltage proving units',
    ],
  },
  {
    id: 'INT-2026-002',
    title: 'Drilling Rig Floor Red-Zone Exclusion & Hands-Free Tooling Mandate',
    category: 'Engineering Control',
    description: 'Installation of high-visibility anti-slip red demarcation flooring and magnetic guide poles to eliminate manual handling of swinging tubulars.',
    triggerSource: 'High SIF Frequency',
    targetSite: 'Naharkatiya Production Station',
    targetActivity: 'Rig Floor Operations',
    associatedRule: 'Safe Mechanical Lifting',
    priority: 'CRITICAL',
    status: 'OPEN',
    assignedOfficer: 'Anup Kumar Barua',
    assignedOfficerRole: 'Drilling Safety Superintendent',
    dueDate: '2026-03-31',
    createdDate: '2026-02-26',
    relatedReportIds: ['OIL-2026-R003'],
    patternId: 'PAT-003',
    actionsTaken: [
      'Safety bulletin issued to all drill crew supervisors',
      'Audit scheduled for Rig OIL-DR-07 and OIL-DR-09',
    ],
  },
  {
    id: 'INT-2026-003',
    title: 'Multi-Level Stratified Gas Testing for Storage Tank Cleansing',
    category: 'Administrative Control',
    description: 'Mandatory 3-level atmospheric stratification sampling and continuous automated datalogging for all tank and vessel entry permits.',
    triggerSource: 'Pattern Detection',
    targetSite: 'Digboi Refinery Asset',
    targetActivity: 'Confined Space Tank Cleaning',
    associatedRule: 'Confined Space',
    priority: 'CRITICAL',
    status: 'UNDER_VERIFICATION',
    assignedOfficer: 'Priyanka Saikia',
    assignedOfficerRole: 'Senior Industrial Hygienist',
    dueDate: '2026-03-10',
    createdDate: '2026-02-10',
    relatedReportIds: ['OIL-2026-R004'],
    patternId: 'PAT-004',
    actionsTaken: [
      'Calibrated 24 optical multi-gas detectors with stratified probe attachments',
      'Conducted live drill on emergency extraction from Tank TK-104',
    ],
    verificationNotes: 'Verification audit conducted on 26-Feb showing 100% compliance on 6 vessel entries.',
    effectivenessRating: 'HIGHLY_EFFECTIVE',
  },
  {
    id: 'INT-2026-004',
    title: 'Continuous Overhead Horizontal Lifelines on Workover Rigs',
    category: 'Engineering Control',
    description: 'Retrofit of stainless steel glider lifelines across all monkey boards and mast structures to ensure unbroken 100% tie-off.',
    triggerSource: 'Life-Saving Rule Non-Compliance',
    targetSite: 'Jorhat Drilling Block',
    targetActivity: 'Working at Height',
    associatedRule: 'Working at Height',
    priority: 'HIGH',
    status: 'CLOSED',
    assignedOfficer: 'Manas Jyoti Dutta',
    assignedOfficerRole: 'Rig HSE Inspector',
    dueDate: '2026-02-28',
    createdDate: '2026-01-15',
    completionDate: '2026-02-25',
    relatedReportIds: ['OIL-2026-R005', 'OIL-2026-R011'],
    patternId: 'PAT-005',
    actionsTaken: [
      'Installed certified lifeline system on rigs WOR-01, WOR-02, WOR-03',
      'Replaced 45 harnesses with twin-tail shock-absorbing lanyards',
    ],
    verificationNotes: 'Full engineering certification received from third-party inspector.',
    effectivenessRating: 'HIGHLY_EFFECTIVE',
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'AUD-9021',
    timestamp: '2026-02-28T10:05:12Z',
    userId: 'USR-003',
    userName: 'Debojit Phukan',
    userRole: 'HSE Analyst',
    action: 'AI_ANALYSIS_COMPLETED',
    entityType: 'AI_MODEL',
    entityId: 'OIL-2026-R001',
    ipAddress: '10.14.22.45',
    status: 'SUCCESS',
    details: 'NLP Precursor Pipeline classified Report OIL-2026-R001 as SIF_POTENTIAL (Confidence: 94%, Rule: Energy Isolation).',
  },
  {
    id: 'AUD-9020',
    timestamp: '2026-02-28T10:00:05Z',
    userId: 'USR-003',
    userName: 'Debojit Phukan',
    userRole: 'HSE Analyst',
    action: 'REPORT_CREATED',
    entityType: 'REPORT',
    entityId: 'OIL-2026-R001',
    ipAddress: '10.14.22.45',
    status: 'SUCCESS',
    details: 'New Unsafe Act submitted for Duliajan Central Complex: Pump motor maintenance initiated prior to circuit breaker lock-out.',
  },
  {
    id: 'AUD-9019',
    timestamp: '2026-02-27T14:35:10Z',
    userId: 'USR-002',
    userName: 'Rajesh Sharma',
    userRole: 'HSE Manager',
    action: 'INTERVENTION_CREATED',
    entityType: 'INTERVENTION',
    entityId: 'INT-2026-002',
    ipAddress: '10.14.20.12',
    status: 'SUCCESS',
    details: 'Created Intervention INT-2026-002 (Drilling Rig Floor Red-Zone Exclusion) assigned to Anup Kumar Barua.',
  },
  {
    id: 'AUD-9018',
    timestamp: '2026-02-27T11:15:00Z',
    userId: 'USR-001',
    userName: 'Ananya Roy',
    userRole: 'Admin',
    action: 'USER_LOGIN',
    entityType: 'AUTH',
    entityId: 'USR-001',
    ipAddress: '10.14.10.5',
    status: 'SUCCESS',
    details: 'User authenticated successfully via Corporate SSO / JWT.',
  },
  {
    id: 'AUD-9017',
    timestamp: '2026-02-26T16:00:00Z',
    userId: 'USR-002',
    userName: 'Rajesh Sharma',
    userRole: 'HSE Manager',
    action: 'PATTERN_IDENTIFIED',
    entityType: 'PATTERN',
    entityId: 'PAT-001',
    ipAddress: '10.14.20.12',
    status: 'WARNING',
    details: 'Precursor pattern PAT-001 (Energy Isolation) crossed critical frequency threshold (247 reports, 81% SIF potential).',
  },
  {
    id: 'AUD-9016',
    timestamp: '2026-02-25T17:00:00Z',
    userId: 'USR-004',
    userName: 'Priyanka Saikia',
    userRole: 'HSE Analyst',
    action: 'INTERVENTION_STATUS_UPDATED',
    entityType: 'INTERVENTION',
    entityId: 'INT-2026-003',
    ipAddress: '10.14.30.88',
    status: 'SUCCESS',
    details: 'Updated status of INT-2026-003 to UNDER_VERIFICATION with audit evidence.',
    changesSummary: {
      before: 'Status: IN_PROGRESS',
      after: 'Status: UNDER_VERIFICATION',
    },
  },
];

export const MOCK_DASHBOARD_DATA: DashboardOverviewResponse = {
  kpis: {
    totalReports: 1428,
    totalReportsTrend: 8.4,
    sifPotentialCount: 384,
    sifPotentialPercentage: 0.269,
    sifTrend: -3.2,
    criticalPrecursorsCount: 42,
    activeInterventionsCount: 14,
    averageResolutionDays: 6.4,
  },
  highRiskSites: [
    {
      site: 'Duliajan Central Complex',
      code: 'DCC-01',
      totalReports: 412,
      sifCount: 138,
      sifRate: 33.5,
      topRule: 'Energy Isolation',
      riskLevel: 'CRITICAL',
      coordinates: [27.3596, 95.3197],
    },
    {
      site: 'Moran Oil & Gas Field',
      code: 'MOR-02',
      totalReports: 326,
      sifCount: 98,
      sifRate: 30.1,
      topRule: 'Hot Work',
      riskLevel: 'CRITICAL',
      coordinates: [27.1852, 94.9312],
    },
    {
      site: 'Naharkatiya Production Station',
      code: 'NHK-03',
      totalReports: 284,
      sifCount: 76,
      sifRate: 26.8,
      topRule: 'Safe Mechanical Lifting',
      riskLevel: 'HIGH',
      coordinates: [27.2833, 95.3333],
    },
    {
      site: 'Digboi Refinery Asset',
      code: 'DGB-04',
      totalReports: 215,
      sifCount: 48,
      sifRate: 22.3,
      topRule: 'Confined Space',
      riskLevel: 'HIGH',
      coordinates: [27.3888, 95.6267],
    },
    {
      site: 'Jorhat Drilling Block',
      code: 'JRH-05',
      totalReports: 119,
      sifCount: 18,
      sifRate: 15.1,
      topRule: 'Working at Height',
      riskLevel: 'MEDIUM',
      coordinates: [26.7509, 94.2037],
    },
    {
      site: 'Kumchai Exploration Field',
      code: 'KUM-06',
      totalReports: 72,
      sifCount: 6,
      sifRate: 8.3,
      topRule: 'Work Authorization',
      riskLevel: 'LOW',
      coordinates: [27.3200, 95.9800],
    },
  ],
  highRiskActivities: [
    {
      activity: 'Maintenance & Overhaul',
      totalReports: 365,
      sifCount: 124,
      sifRate: 34.0,
      primaryHazard: 'Electrical & Pressurized Energy',
      riskLevel: 'CRITICAL',
    },
    {
      activity: 'Rig Floor Operations',
      totalReports: 290,
      sifCount: 94,
      sifRate: 32.4,
      primaryHazard: 'Suspended Loads & Rotary Machinery',
      riskLevel: 'CRITICAL',
    },
    {
      activity: 'Hot Work & Pipe Welding',
      totalReports: 245,
      sifCount: 72,
      sifRate: 29.4,
      primaryHazard: 'Hydrocarbon Gas & Sparks',
      riskLevel: 'HIGH',
    },
    {
      activity: 'Confined Space Tank Cleaning',
      totalReports: 148,
      sifCount: 44,
      sifRate: 29.7,
      primaryHazard: 'Toxic H2S & Oxygen Depletion',
      riskLevel: 'HIGH',
    },
    {
      activity: 'Working at Height',
      totalReports: 180,
      sifCount: 38,
      sifRate: 21.1,
      primaryHazard: 'Elevated Falls & Dropped Objects',
      riskLevel: 'MEDIUM',
    },
    {
      activity: 'Pipeline Pressure Testing',
      totalReports: 112,
      sifCount: 22,
      sifRate: 19.6,
      primaryHazard: 'High Hydraulic Pressure',
      riskLevel: 'MEDIUM',
    },
    {
      activity: 'Heavy Logistics & Transport',
      totalReports: 88,
      sifCount: 12,
      sifRate: 13.6,
      primaryHazard: 'Vehicle Dynamics on Rough Roads',
      riskLevel: 'LOW',
    },
  ],
  topLifeSavingRules: [
    { rule: 'Energy Isolation', count: 312, sifCount: 118, percentage: 37.8, trend: 'increasing', iconKey: 'ZapOff' },
    { rule: 'Hot Work', count: 268, sifCount: 84, percentage: 31.3, trend: 'increasing', iconKey: 'Flame' },
    { rule: 'Safe Mechanical Lifting', count: 242, sifCount: 76, percentage: 31.4, trend: 'stable', iconKey: 'Anchor' },
    { rule: 'Confined Space', count: 184, sifCount: 52, percentage: 28.3, trend: 'decreasing', iconKey: 'Box' },
    { rule: 'Line of Fire', count: 176, sifCount: 46, percentage: 26.1, trend: 'stable', iconKey: 'Crosshair' },
    { rule: 'Working at Height', count: 142, sifCount: 32, percentage: 22.5, trend: 'decreasing', iconKey: 'ArrowUpCircle' },
    { rule: 'Bypassing Safety Controls', count: 98, sifCount: 24, percentage: 24.5, trend: 'increasing', iconKey: 'ShieldAlert' },
    { rule: 'Driving', count: 82, sifCount: 10, percentage: 12.2, trend: 'stable', iconKey: 'Truck' },
    { rule: 'Work Authorization', count: 68, sifCount: 8, percentage: 11.8, trend: 'decreasing', iconKey: 'FileCheck' },
  ],
  precursorFailures: [
    { activity: 'Maintenance', barrierFailure: 'Lockout/Tagout Omission', hazard: 'High-Voltage / Pressure', incidentCount: 124, sifRate: 84.5, riskScore: 92, rule: 'Energy Isolation' },
    { activity: 'Hot Work', barrierFailure: 'Spark Barrier / Gas Test Failure', hazard: 'Flammables & Condensate', incidentCount: 78, sifRate: 79.2, riskScore: 88, rule: 'Hot Work' },
    { activity: 'Rig Floor', barrierFailure: 'Exclusion Zone Breach', hazard: 'Suspended Tubulars', incidentCount: 65, sifRate: 72.0, riskScore: 84, rule: 'Line of Fire' },
    { activity: 'Tank Cleaning', barrierFailure: 'Stratified Gas Sampling Omission', hazard: 'H2S Toxic Atmosphere', incidentCount: 44, sifRate: 88.0, riskScore: 94, rule: 'Confined Space' },
    { activity: 'Height Works', barrierFailure: '100% Tie-Off Disconnect', hazard: 'Fall > 6m', incidentCount: 38, sifRate: 68.4, riskScore: 76, rule: 'Working at Height' },
  ],
  trends: [
    { date: 'Sep 2025', totalReports: 195, sifPotential: 58, nonSif: 137, nearMisses: 42 },
    { date: 'Oct 2025', totalReports: 210, sifPotential: 62, nonSif: 148, nearMisses: 49 },
    { date: 'Nov 2025', totalReports: 228, sifPotential: 64, nonSif: 164, nearMisses: 54 },
    { date: 'Dec 2025', totalReports: 240, sifPotential: 69, nonSif: 171, nearMisses: 58 },
    { date: 'Jan 2026', totalReports: 265, sifPotential: 71, nonSif: 194, nearMisses: 63 },
    { date: 'Feb 2026', totalReports: 290, sifPotential: 60, nonSif: 230, nearMisses: 70 },
  ],
  lastUpdated: '2026-02-28T10:15:00Z',
};
