"""
grounding_validator.py - Stage 20 Safety Recommendation Grounding & Hallucination Guard.
Evaluates every generated safety recommendation against retrieved PDF evidence passages.
Filters out unsupported recommendations and enforces 100% source-grounded safety outputs.
"""

import re
import logging
from typing import Dict, List, Any, Optional
from pydantic import BaseModel, Field

logger = logging.getLogger("OILPS_GroundingValidator")


class RecommendationValidationResult(BaseModel):
    recommendation: str = Field(..., description="The evaluated safety recommendation text.")
    status: str = Field(..., description="Validation status: SUPPORTED, PARTIALLY_SUPPORTED, or UNSUPPORTED.")
    grounding_score: float = Field(..., description="Calculated support confidence score (0.0 to 1.0).")
    supporting_document: Optional[str] = Field(default=None, description="Primary supporting PDF document filename.")
    supporting_page: Optional[int] = Field(default=None, description="Primary supporting page number.")
    supporting_section: Optional[str] = Field(default=None, description="Primary supporting section header.")
    supporting_chunk_id: Optional[str] = Field(default=None, description="Unique chunk ID of supporting evidence.")
    evidence_snippet: Optional[str] = Field(default=None, description="Relevant supporting text passage snippet.")


class Stage20GroundingAudit(BaseModel):
    total_generated: int = Field(..., description="Total recommendations generated by LLM/Extractive module.")
    supported_count: int = Field(..., description="Number of fully supported recommendations retained.")
    partially_supported_count: int = Field(..., description="Number of partially supported recommendations retained.")
    unsupported_count: int = Field(..., description="Number of unsupported recommendations detected.")
    removed_count: int = Field(..., description="Number of unsupported recommendations removed.")
    grounding_rate: float = Field(..., description="Supported recommendations / Total generated (0.0 to 1.0).")
    unsupported_rate: float = Field(..., description="Unsupported recommendations / Total generated (0.0 to 1.0).")
    overall_status: str = Field(..., description="GROUNDED, PARTIALLY_GROUNDED, UNSUPPORTED, or NO_EVIDENCE.")
    validations: List[RecommendationValidationResult] = Field(default_factory=list)
    removed_recommendations: List[str] = Field(default_factory=list)


class GroundingValidator:
    """
    Production Grounding Validator operating AFTER recommendation generation.
    Enforces strict evidence support, authorative source prioritization, and hallucination rejection.
    """

    def __init__(self, min_support_threshold: float = 0.25):
        self.min_support_threshold = min_support_threshold
        # Document priority multipliers
        self.doc_weights = {
            "IOGP Life-Saving Rules.pdf": 1.25,
            "Process Safety Fundamentals.pdf": 1.15,
            "Safety performance indicators – 2025 data.pdf": 0.95,
            "Safety performance indicators – 2024 data.pdf": 0.95,
            "Safety performance indicators – 2023 data.pdf": 0.95,
        }

    def _clean_text(self, text: str) -> List[str]:
        """Extract clean lowercase keywords > 3 chars for term matching."""
        words = re.findall(r'\b[a-zA-Z]{4,}\b', text.lower())
        stopwords = {"this", "that", "with", "from", "have", "been", "were", "what", "which", "when", "where", "must", "should", "shall", "will", "does"}
        return [w for w in words if w not in stopwords]

    def validate_single_recommendation(
        self,
        recommendation: str,
        retrieved_passages: List[Dict[str, Any]]
    ) -> RecommendationValidationResult:
        """
        Validate a single recommendation against retrieved PDF evidence passages.
        """
        rec_words = set(self._clean_text(recommendation))
        if not rec_words:
            return RecommendationValidationResult(
                recommendation=recommendation,
                status="UNSUPPORTED",
                grounding_score=0.0
            )

        best_score = 0.0
        best_passage = None

        for passage in retrieved_passages:
            doc_name = passage.get("document", "")
            doc_weight = self.doc_weights.get(doc_name, 1.0)

            passage_words = set(self._clean_text(passage.get("text", "")))
            if not passage_words:
                continue

            overlap = rec_words.intersection(passage_words)
            raw_score = len(overlap) / (len(rec_words) + 1e-5)
            weighted_score = raw_score * doc_weight

            # Check domain hazard keyword match
            domain_terms = [
                "isolation", "pressure", "bleeder", "valve", "confined", "entry",
                "lifting", "h2s", "gas", "toxic", "atmosphere", "permit", "respiratory",
                "ventilation", "monitor", "detector", "vessel", "barrier", "hazard",
                "first-aid", "housekeeping", "load", "fire", "welding", "hot", "work",
                "flash", "manifold", "fuel"
            ]
            if any(term in recommendation.lower() and term in passage.get("text", "").lower() for term in domain_terms):
                weighted_score += 0.15

            if weighted_score > best_score:
                best_score = weighted_score
                best_passage = passage

        best_score = round(min(1.0, best_score), 4)

        if best_score >= 0.30:
            status = "SUPPORTED"
        elif best_score >= self.min_support_threshold:
            status = "PARTIALLY_SUPPORTED"
        else:
            status = "UNSUPPORTED"

        doc = best_passage.get("document") if best_passage else None
        page = best_passage.get("page") if best_passage else None
        sec = best_passage.get("section", "General") if best_passage else None
        cid = best_passage.get("chunk_id") if best_passage else None
        snippet = (best_passage.get("text", "")[:140] + "...") if best_passage else None

        return RecommendationValidationResult(
            recommendation=recommendation,
            status=status,
            grounding_score=best_score,
            supporting_document=doc,
            supporting_page=page,
            supporting_section=sec,
            supporting_chunk_id=cid,
            evidence_snippet=snippet
        )

    def validate_and_filter(
        self,
        recommendation_payload: Dict[str, Any],
        retrieved_passages: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Validate all generated recommendations, remove unsupported items, and compute audit metrics.
        """
        imm = recommendation_payload.get("immediate_actions", [])
        ver = recommendation_payload.get("verification_actions", recommendation_payload.get("control_verification", []))
        esc = recommendation_payload.get("escalation_actions", recommendation_payload.get("escalation", []))
        prev = recommendation_payload.get("preventive_actions", [])

        action_groups = [
            ("immediate_actions", imm),
            ("verification_actions", ver),
            ("escalation_actions", esc),
            ("preventive_actions", prev)
        ]

        validations = []
        filtered_payload = dict(recommendation_payload)
        removed_recs = []

        total_gen = 0
        supported_cnt = 0
        partially_cnt = 0
        unsupported_cnt = 0

        for key, rec_list in action_groups:
            clean_list = []
            for rec_item in rec_list:
                total_gen += 1
                v_res = self.validate_single_recommendation(rec_item, retrieved_passages)
                validations.append(v_res)

                if v_res.status in ["SUPPORTED", "PARTIALLY_SUPPORTED"]:
                    clean_list.append(rec_item)
                    if v_res.status == "SUPPORTED":
                        supported_cnt += 1
                    else:
                        partially_cnt += 1
                else:
                    unsupported_cnt += 1
                    removed_recs.append(rec_item)
                    logger.warning(f"GroundingValidator REMOVED UNSUPPORTED RECOMMENDATION: '{rec_item}' (score={v_res.grounding_score})")

            filtered_payload[key] = clean_list

        # Maintain aliases for backward compatibility
        filtered_payload["control_verification"] = filtered_payload.get("verification_actions", [])
        filtered_payload["escalation"] = filtered_payload.get("escalation_actions", [])

        g_rate = (supported_cnt + partially_cnt) / total_gen if total_gen > 0 else 1.0
        u_rate = unsupported_cnt / total_gen if total_gen > 0 else 0.0

        if (supported_cnt + partially_cnt) > 0:
            overall_status = "GROUNDED"
        elif not retrieved_passages:
            overall_status = "NO_EVIDENCE"
        else:
            overall_status = "UNSUPPORTED"

        audit = Stage20GroundingAudit(
            total_generated=total_gen,
            supported_count=supported_cnt,
            partially_supported_count=partially_cnt,
            unsupported_count=unsupported_cnt,
            removed_count=len(removed_recs),
            grounding_rate=round(g_rate, 4),
            unsupported_rate=round(u_rate, 4),
            overall_status=overall_status,
            validations=validations,
            removed_recommendations=removed_recs
        )

        filtered_payload["grounding"] = bool(overall_status == "GROUNDED")
        filtered_payload["recommendation_status"] = overall_status
        filtered_payload["grounding_audit"] = audit.model_dump()

        return filtered_payload


if __name__ == "__main__":
    validator = GroundingValidator()
    test_recs = {
        "immediate_actions": [
            "Initiate immediate Stop Work Authority and depressurize pressure line.",
            "Verify aviation fuel quality and helideck net integrity." # UNSUPPORTED HALLUCINATION TEST
        ],
        "verification_actions": [
            "Test for trapped pressure before loosening bleeder plug."
        ]
    }
    passages = [
        {
            "document": "IOGP Life-Saving Rules.pdf",
            "page": 12,
            "section": "Energy Isolation",
            "chunk_id": "c1",
            "text": "Verify isolation and zero energy state before work begins. Test for trapped pressure before loosening fittings or bleeder plugs."
        }
    ]
    res = validator.validate_and_filter(test_recs, passages)
    print("Overall Status:", res["recommendation_status"])
    print("Removed Count:", res["grounding_audit"]["removed_count"])
    print("Remaining Immediate Actions:", res["immediate_actions"])
